1) Загрузите в колаб файлы по оценкам (ratings) и фильмам (movies) и создайте на их основе pandas-датафреймы

In [ ]:
import pandas as pd

Создаём ДФ для таблицы с рейтингом

In [ ]:
df_ratings = pd.read_csv("u.data.csv", names=['user_id', 'movie_id', 'rating', 'timestamp'], header=None, sep='\t', encoding = "ISO-8859-1")
df_ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

ДФ для таблицы с фильмами

In [ ]:
df_movies = pd.read_csv("u.item.csv", names=['movie_id', 'movie_title', 'release_date', 'video_release_date', 'IMDb_URL', 'unknown', 'Action', 'Adventure', 'Animation',
              'Children',  'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'], header=None, sep='|', encoding = "ISO-8859-1")
df_movies.head()

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

2) Средствами Pandas, используя dataframe ratings, найдите id пользователя, поставившего больше всего оценок

In [ ]:
df_ratings.groupby('user_id').agg({'rating': 'count'}). sort_values('rating', ascending=False)

         rating
user_id
405         737
655         685
13          636
450         540
276         518
...         ...
685          20
475          20
36           20
732          20
596          20

[943 rows x 1 columns]

3) Оставьте в датафрейме ratings только те фильмы, который оценил данный пользователь

In [ ]:
df_ratings = df_ratings.loc[df_ratings['user_id']==405]
df_ratings.head()

       user_id  movie_id  rating  timestamp
12276      405        56       4  885544911
12383      405       592       1  885548670
12430      405      1582       1  885548670
12449      405       171       1  885549544
12460      405       580       1  885547447

4) Добавьте к датафрейму из задания 3 столбцы: По жанрам. Каждый столбец - это жанр. Единицу записываем, если фильм принадлежит данному жанру и 0 - если нет столбцы с общим количеством оценок от всех пользователей на фильм и суммарной оценкой от всех пользователей

In [ ]:
count_ratimg = df_ratings['movie_id'].value_counts().reset_index().rename(columns={'index':'movie_id', 'movie_id':'count_ratings'})
count_ratimg.head()

   movie_id  count_ratings
0        50            583
1       258            509
2       100            508
3       181            507
4       294            485

In [ ]:
sum_rating = df_ratings[['movie_id','rating']].groupby('movie_id').sum().reset_index().rename(columns={'rating':'sum_ratings'})
sum_rating.head()

   movie_id  sum_ratings
0         1         1753
1         2          420
2         3          273
3         4          742
4         5          284

In [ ]:
df_movies['release_date']=pd.to_datetime(df_movies['release_date'])
df_movies['year'] = df_movies['release_date'].dt.year
df_movies.head()

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
0,1,Toy Story (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,1995.0
1,2,GoldenEye (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,1,0,0,1995.0
2,3,Four Rooms (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1995.0
3,4,Get Shorty (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1995.0
4,5,Copycat (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1995.0

Соединяем полученные результаты

In [ ]:
df_r1=df_movies.merge(sum_rating, left_on='movie_id', right_on='movie_id', how='inner')
df_r1.head()

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children,...,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year,sum_ratings
0,1,Toy Story (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,1995.0,1753
1,2,GoldenEye (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,1,0,0,1995.0,420
2,3,Four Rooms (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1995.0,273
3,4,Get Shorty (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1995.0,742
4,5,Copycat (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,1,0,0,1995.0,284

In [ ]:
df_r1=df_r1.merge(count_ratimg, left_on='movie_id', right_on='movie_id', how='inner')
df_r1.head()

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children,...,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year,sum_ratings,count_ratings
0,1,Toy Story (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,1995.0,1753,452
1,2,GoldenEye (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,1,0,0,1995.0,420,131
2,3,Four Rooms (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,1,0,0,1995.0,273,90
3,4,Get Shorty (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,1995.0,742,209
4,5,Copycat (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,1,0,0,1995.0,284,86

In [ ]:
df_r1=df_r1.merge(df_ratings, left_on='movie_id', right_on='movie_id', how='inner')
df_r1.head()

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children,...,Sci-Fi,Thriller,War,Western,year,sum_ratings,count_ratings,user_id,rating,timestamp
0,2,GoldenEye (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,1,0,0,1995.0,420,131,405,1,885547953
1,4,Get Shorty (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,1995.0,742,209,405,4,885547314
2,5,Copycat (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,1,0,0,1995.0,284,86,405,4,885545070
3,8,Babe (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Babe%20(1995),0,0,0,0,1,...,0,0,0,0,1995.0,875,219,405,4,885545015
4,11,Seven (Se7en) (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Se7en%20(1995),0,0,0,0,0,...,0,1,0,0,1995.0,908,236,405,4,885545263

Удаляем лишние колонки

In [ ]:
df_r1 =df_r1.drop(['release_date','movie_id','movie_title','video_release_date','IMDb_URL','user_id','timestamp'],axis=1)
df_r1.head()

,unknown,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,year,sum_ratings,count_ratings,rating
0,0,1,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1995.0,420,131,1
1,0,1,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,1995.0,742,209,4
2,0,0,0,0,0,0,1,0,1,0,...,0,0,0,1,0,0,1995.0,284,86,4
3,0,0,0,0,1,1,0,0,1,0,...,0,0,0,0,0,0,1995.0,875,219,4
4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,1995.0,908,236,4

5) Сформируйте X_train, X_test, y_train, y_test

In [ ]:
df_r1.columns

Index(['unknown', 'Action', 'Adventure', 'Animation', 'Children', 'Comedy',
       'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western',
       'year', 'sum_ratings', 'count_ratings', 'rating'],
      dtype='object')

In [ ]:
x, y = df_r1 [['unknown','Action','Adventure','Animation','Children','Comedy',
       'Crime','Documentary','Drama','Fantasy','Film-Noir','Horror',
       'Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western','sum_ratings','count_ratings','year']],df_r1['rating']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_tast, y_train , y_test = train_test_split (x, y, test_size = 0.2)

6) Возьмите модель линейной регрессии (или любую другую для задачи регрессии)  и обучите ее на фильмах

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression ()

In [ ]:
model.fit (x_train, y_train)

LinearRegression()

In [ ]:
from sklearn.metrics import mean_squared_error

7) Оцените качество модели на X_test, y_test при помощи метрик для задачи регрессии

In [ ]:
mean_squared_error(y_train , model.predict (x_train))

1.097895656908266

8) Загрузить данные в spark

In [ ]:
!apt-get update

Ign:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Get:2 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Ign:3 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [696 B]
Hit:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:8 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Hit:9 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:10 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ Packages [80.4 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:13 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Get:14 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [931 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:16 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease [15.9 kB]
Hit:17 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:18 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,479 kB]
Get:19 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main Sources [1,827 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3,067 kB]
Get:21 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2,628 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,257 kB]
Get:23 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main amd64 Packages [936 kB]
Get:24 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic/main amd64 Packages [45.2 kB]
Fetched 13.5 MB in 4s (3,161 kB/s)
Reading package lists... Done

In [ ]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

In [ ]:
!wget -q https://downloads.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop2.7.tgz

In [ ]:
!tar -xvf spark-3.2.1-bin-hadoop2.7.tgz

spark-3.2.1-bin-hadoop2.7/
spark-3.2.1-bin-hadoop2.7/LICENSE
spark-3.2.1-bin-hadoop2.7/NOTICE
spark-3.2.1-bin-hadoop2.7/R/
spark-3.2.1-bin-hadoop2.7/R/lib/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/DESCRIPTION
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/INDEX
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/Rd.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/features.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/hsearch.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/links.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/nsInfo.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/package.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/NAMESPACE
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/SparkR
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdb
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdx
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/AnIndex
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdb
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdx
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/aliases.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/paths.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/html/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/html/00Index.html
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/html/R.css
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/profile/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/profile/general.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/profile/shell.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/tests/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/tests/testthat/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/tests/testthat/test_basic.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/worker/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/worker/daemon.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/worker/worker.R
spark-3.2.1-bin-hadoop2.7/R/lib/sparkr.zip
spark-3.2.1-bin-hadoop2.7/README.md
spark-3.2.1-bin-hadoop2.7/RELEASE
spark-3.2.1-bin-hadoop2.7/bin/
spark-3.2.1-bin-hadoop2.7/bin/beeline
spark-3.2.1-bin-hadoop2.7/bin/beeline.cmd
spark-3.2.1-bin-hadoop2.7/bin/docker-image-tool.sh
spark-3.2.1-bin-hadoop2.7/bin/find-spark-home
spark-3.2.1-bin-hadoop2.7/bin/find-spark-home.cmd
spark-3.2.1-bin-hadoop2.7/bin/load-spark-env.cmd
spark-3.2.1-bin-hadoop2.7/bin/load-spark-env.sh
spark-3.2.1-bin-hadoop2.7/bin/pyspark
spark-3.2.1-bin-hadoop2.7/bin/pyspark.cmd
spark-3.2.1-bin-hadoop2.7/bin/pyspark2.cmd
spark-3.2.1-bin-hadoop2.7/bin/run-example
spark-3.2.1-bin-hadoop2.7/bin/run-example.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-class
spark-3.2.1-bin-hadoop2.7/bin/spark-class.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-class2.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-shell
spark-3.2.1-bin-hadoop2.7/bin/spark-shell.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-shell2.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-sql
spark-3.2.1-bin-hadoop2.7/bin/spark-sql.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-sql2.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-submit
spark-3.2.1-bin-hadoop2.7/bin/spark-submit.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-submit2.cmd
spark-3.2.1-bin-hadoop2.7/bin/sparkR
spark-3.2.1-bin-hadoop2.7/bin/sparkR.cmd
spark-3.2.1-bin-hadoop2.7/bin/sparkR2.cmd
spark-3.2.1-bin-hadoop2.7/conf/
spark-3.2.1-bin-hadoop2.7/conf/fairscheduler.xml.template
spark-3.2.1-bin-hadoop2.7/conf/log4j.properties.template
spark-3.2.1-bin-hadoop2.7/conf/metrics.properties.template
spark-3.2.1-bin-hadoop2.7/conf/spark-defaults.conf.template
spark-3.2.1-bin-hadoop2.7/conf/spark-env.sh.template
spark-3.2.1-bin-hadoop2.7/conf/workers.template
spark-3.2.1-bin-hadoop2.7/data/
spark-3.2.1-bin-hadoop2.7/data/graphx/
spark-3.2.1-bin-hadoop2.7/data/graphx/followers.txt
spark-3.2.1-bin-hadoop2.7/data/graphx/users.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/
spark-3.2.1-bin-hadoop2.7/data/mllib/als/
spark-3.2.1-bin-hadoop2.7/data/mllib/als/sample_movielens_ratings.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/als/test.data
spark-3.2.1-bin-hadoop2.7/data/mllib/gmm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/license.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/29.5.a_b_EGDP022204.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/54893.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/DP153539.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/DP802813.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/not-image.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/license.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/BGRA.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/BGRA_alpha_60.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/chr30.4.184.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/grayscale.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/29.5.a_b_EGDP022204.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/not-image.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/54893.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP153539.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP802813.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA_alpha_60.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/chr30.4.184.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/grayscale.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/iris_libsvm.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/kmeans_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/pagerank_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/pic_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/ridge-data/
spark-3.2.1-bin-hadoop2.7/data/mllib/ridge-data/lpsa.data
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_binary_classification_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_fpgrowth.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_isotonic_regression_libsvm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_kmeans_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_lda_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_lda_libsvm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_libsvm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_linear_regression_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_movielens_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_multiclass_classification_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_svm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/streaming_kmeans_data_test.txt
spark-3.2.1-bin-hadoop2.7/data/streaming/
spark-3.2.1-bin-hadoop2.7/data/streaming/AFINN-111.txt
spark-3.2.1-bin-hadoop2.7/examples/
spark-3.2.1-bin-hadoop2.7/examples/jars/
spark-3.2.1-bin-hadoop2.7/examples/jars/scopt_2.12-3.7.1.jar
spark-3.2.1-bin-hadoop2.7/examples/jars/spark-examples_2.12-3.2.1.jar
spark-3.2.1-bin-hadoop2.7/examples/src/
spark-3.2.1-bin-hadoop2.7/examples/src/main/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaHdfsLR.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaLogQuery.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaPageRank.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaSparkPi.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaStatusTrackerDemo.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaTC.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaWordCount.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaAFTSurvivalRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaALSExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBinarizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBisectingKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketedRandomProjectionLSHExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSqSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSquareTestExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCorrelationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCountVectorizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDCTExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeClassificationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDocument.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaElementwiseProductExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaEstimatorTransformerParamExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFMClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFMRegressorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFPGrowthExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFeatureHasherExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGaussianMixtureExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGeneralizedLinearRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeRegressorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaImputerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaIndexToStringExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaInteractionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaIsotonicRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLDAExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLabeledDocument.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearRegressionWithElasticNetExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearSVCExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionSummaryExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionWithElasticNetExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMaxAbsScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMinHashLSHExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMinMaxScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaCrossValidationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaTrainValidationSplitExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMulticlassLogisticRegressionWithElasticNetExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMultilayerPerceptronClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNGramExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNaiveBayesExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNormalizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaOneHotEncoderExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaOneVsRestExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPCAExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPipelineExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPolynomialExpansionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPowerIterationClusteringExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPrefixSpanExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaQuantileDiscretizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRFormulaExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestRegressorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRobustScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaSQLTransformerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStandardScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStopWordsRemoverExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStringIndexerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaSummarizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaTfIdfExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaTokenizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaUnivariateFeatureSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVarianceThresholdSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorAssemblerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorIndexerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSizeHintExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSlicerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaWord2VecExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaALS.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaAssociationRulesExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaBinaryClassificationMetricsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaBisectingKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaChiSqSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaCorrelationsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeClassificationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaElementwiseProductExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGaussianMixtureExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingClassificationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingKolmogorovSmirnovTestExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaIsotonicRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaKernelDensityEstimationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLBFGSExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLatentDirichletAllocationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLogisticRegressionWithLBFGSExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaMultiLabelClassificationMetricsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaMulticlassClassificationMetricsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaNaiveBayesExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPCAExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPowerIterationClusteringExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPrefixSpanExample.java

In [ ]:
!pip install -q findspark

In [ ]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.2.1-bin-hadoop2.7"

In [ ]:
import findspark
findspark.init()
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

9) Средствами спарка вывести среднюю оценку для каждого фильма

In [ ]:
df_d=spark.read.csv('u.data.csv',header=None,sep='\t',inferSchema=True)
df_d.show()

+---+----+---+---------+
|_c0| _c1|_c2|      _c3|
+---+----+---+---------+
|196| 242|  3|881250949|
|186| 302|  3|891717742|
| 22| 377|  1|878887116|
|244|  51|  2|880606923|
|166| 346|  1|886397596|
|298| 474|  4|884182806|
|115| 265|  2|881171488|
|253| 465|  5|891628467|
|305| 451|  3|886324817|
|  6|  86|  3|883603013|
| 62| 257|  2|879372434|
|286|1014|  5|879781125|
|200| 222|  5|876042340|
|210|  40|  3|891035994|
|224|  29|  3|888104457|
|303| 785|  3|879485318|
|122| 387|  5|879270459|
|194| 274|  2|879539794|
|291|1042|  4|874834944|
|234|1184|  2|892079237|
+---+----+---+---------+
only showing top 20 rows

In [ ]:
df_d=df_d.toDF('user_id','movie_id','rating','timestamp')
df_d.show()

+-------+--------+------+---------+
|user_id|movie_id|rating|timestamp|
+-------+--------+------+---------+
|    196|     242|     3|881250949|
|    186|     302|     3|891717742|
|     22|     377|     1|878887116|
|    244|      51|     2|880606923|
|    166|     346|     1|886397596|
|    298|     474|     4|884182806|
|    115|     265|     2|881171488|
|    253|     465|     5|891628467|
|    305|     451|     3|886324817|
|      6|      86|     3|883603013|
|     62|     257|     2|879372434|
|    286|    1014|     5|879781125|
|    200|     222|     5|876042340|
|    210|      40|     3|891035994|
|    224|      29|     3|888104457|
|    303|     785|     3|879485318|
|    122|     387|     5|879270459|
|    194|     274|     2|879539794|
|    291|    1042|     4|874834944|
|    234|    1184|     2|892079237|
+-------+--------+------+---------+
only showing top 20 rows

In [ ]:
df_i=spark.read.csv('u.item.csv',header=None,sep='|',inferSchema=True)
df_i.show()

+---+--------------------+-----------+----+--------------------+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
|_c0|                 _c1|        _c2| _c3|                 _c4|_c5|_c6|_c7|_c8|_c9|_c10|_c11|_c12|_c13|_c14|_c15|_c16|_c17|_c18|_c19|_c20|_c21|_c22|_c23|
+---+--------------------+-----------+----+--------------------+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
|  1|    Toy Story (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  1|  1|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
|  2|    GoldenEye (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  1|  1|  0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   1|   0|   0|
|  3|   Four Rooms (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   1|   0|   0|
|  4|   Get Shorty (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  1|  0|  0|  0|   1|   0|   0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
|  5|      Copycat (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   1|   0|   1|   0|   0|   0|   0|   0|   0|   0|   1|   0|   0|
|  6|Shanghai Triad (Y...|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   0|   0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
|  7|Twelve Monkeys (1...|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   0|   0|   1|   0|   0|   0|   0|   0|   0|   1|   0|   0|   0|
|  8|         Babe (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  1|   1|   0|   0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
|  9|Dead Man Walking ...|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   0|   0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
| 10|  Richard III (1995)|22-Jan-1996|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   0|   0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   1|   0|
| 11|Seven (Se7en) (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   1|   0|   0|
| 12|Usual Suspects, T...|14-Aug-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   1|   0|   0|
| 13|Mighty Aphrodite ...|30-Oct-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
| 14|  Postino, Il (1994)|01-Jan-1994|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   0|   0|   1|   0|   0|   0|   0|   0|   1|   0|   0|   0|   0|
| 15|Mr. Holland's Opu...|29-Jan-1996|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   0|   0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
| 16|French Twist (Gaz...|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   1|   0|   0|   0|   0|
| 17|From Dusk Till Da...|05-Feb-1996|null|http://us.imdb.co...|  0|  1|  0|  0|  0|   1|   1|   0|   0|   0|   0|   1|   0|   0|   0|   0|   1|   0|   0|
| 18|White Balloon, Th...|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   0|   0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
| 19|Antonia's Line (1...|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   0|   0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
| 20|Angels and Insect...|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   0|   0|   1|   0|   0|   0|   0|   0|   1|   0|   0|   0|   0|
+---+--------------------+-----------+----+--------------------+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
only showing top 20 rows

In [ ]:
df_i=df_i.toDF('movie_id','movie_title','release_date','video_release_date','IMDb_URL','unknown','Action','Adventure','Animation',
              'Children','Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western')
df_i.show()

+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|movie_id|         movie_title|release_date|video_release_date|            IMDb_URL|unknown|Action|Adventure|Animation|Children|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller|War|Western|
+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|       1|    Toy Story (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        1|       1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       2|    GoldenEye (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        1|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       3|   Four Rooms (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       4|   Get Shorty (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        0|        0|       0|     1|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       5|      Copycat (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       6|Shanghai Triad (Y...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       7|Twelve Monkeys (1...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     1|       0|  0|      0|
|       8|         Babe (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       1|     1|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       9|Dead Man Walking ...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      10|  Richard III (1995)| 22-Jan-1996|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  1|      0|
|      11|Seven (Se7en) (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    1|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|      12|Usual Suspects, T...| 14-Aug-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    1|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|      13|Mighty Aphrodite ...| 30-Oct-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      14|  Postino, Il (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|
|      15|Mr. Holland's Opu...| 29-Jan-1996|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      16|French Twist (Gaz...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|
|      17|From Dusk Till Da...| 05-Feb-1996|              null|http://us.imdb.co...|      0|     1|        0|        0|       0|     1|    1|          0|    0|      0|        0|     1|      0|      0|      0|     0|       1|  0|      0|
|      18|White Balloon, Th...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      19|Antonia's Line (1...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      20|Angels and Insect...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|
+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 20 rows

In [ ]:
df_j=df_i.join(df_d, 'movie_id', how= 'inner')

In [ ]:
df_j.show()

+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+-------+------+---------+
|movie_id|         movie_title|release_date|video_release_date|            IMDb_URL|unknown|Action|Adventure|Animation|Children|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller|War|Western|user_id|rating|timestamp|
+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+-------+------+---------+
|     242|        Kolya (1996)| 24-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|    196|     3|881250949|
|     302|L.A. Confidential...| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    1|          0|    0|      0|        1|     0|      0|      1|      0|     0|       1|  0|      0|    186|     3|891717742|
|     377| Heavyweights (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|       1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|     22|     1|878887116|
|      51|Legends of the Fa...| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  1|      1|    244|     2|880606923|
|     346| Jackie Brown (1997)| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|    166|     1|886397596|
|     474|Dr. Strangelove o...| 01-Jan-1963|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     1|       0|  1|      0|    298|     4|884182806|
|     265|Hunt for Red Octo...| 01-Jan-1990|              null|http://us.imdb.co...|      0|     1|        0|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|    115|     2|881171488|
|     465|Jungle Book, The ...| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        1|        0|       1|     0|    0|          0|    0|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|    253|     5|891628467|
|     451|       Grease (1978)| 01-Jan-1978|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      1|      0|      1|     0|       0|  0|      0|    305|     3|886324817|
|      86|Remains of the Da...| 01-Jan-1993|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|      6|     3|883603013|
|     257| Men in Black (1997)| 04-Jul-1997|              null|http://us.imdb.co...|      0|     1|        1|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     1|       0|  0|      0|     62|     2|879372434|
|    1014|Romy and Michele'...| 25-Apr-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|    286|     5|879781125|
|     222|Star Trek: First ...| 22-Nov-1996|              null|http://us.imdb.co...|      0|     1|        1|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     1|       0|  0|      0|    200|     5|876042340|
|      40|To Wong Foo, Than...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|    210|     3|891035994|
|      29|Batman Forever (1...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        1|        0|       0|     1|    1|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|    224|     3|888104457|
|     785|     Only You (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|    303|     3|879485318|
|     387|Age of Innocence,...| 01-Jan-1993|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|    122|     5|879270459|
|     274|      Sabrina (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|    194|     2|879539794|
|    1042|   Just Cause (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      1|      0|     0|       1|  0|      0|    291|     4|874834944|
|    1184|Endless Summer 2,...| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          1|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|    234|     2|892079237|
+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+-------+------+---------+
only showing top 20 rows

In [ ]:
df_avg= df_j.groupBy ('movie_title'). avg('rating')
df_avg.show()

+--------------------+------------------+
|         movie_title|       avg(rating)|
+--------------------+------------------+
|   Annie Hall (1977)| 3.911111111111111|
|Heavenly Creature...|3.6714285714285713|
|       Psycho (1960)| 4.100418410041841|
|Snow White and th...|3.7093023255813953|
|Night of the Livi...|          3.421875|
|When We Were King...| 4.045454545454546|
| If Lucy Fell (1996)|2.7586206896551726|
|    Fair Game (1995)|2.1818181818181817|
| Three Wishes (1995)|3.2222222222222223|
|         Cosi (1996)|               4.0|
|Paris, France (1993)|2.3333333333333335|
|Spanking the Monk...| 3.074074074074074|
|I'll Do Anything ...|               2.6|
|        Mondo (1996)|               3.0|
| Evil Dead II (1987)|3.5168539325842696|
|    Threesome (1994)| 2.838709677419355|
|Last Action Hero ...|2.7457627118644066|
|Reality Bites (1994)| 2.961038961038961|
|Colonel Chabert, ...|               3.5|
|   Blue Chips (1994)|2.6666666666666665|
+--------------------+------------------+
only showing top 20 rows

10) Посчитайте средствами спарка среднюю оценку для каждого жанра

In [ ]:
df_avg_gener= df_j.groupBy ('unknown','Action','Adventure','Animation',
              'Children','Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western'). avg('rating')
df_avg_gener.show()

+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+------------------+
|unknown|Action|Adventure|Animation|Children|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller|War|Western|       avg(rating)|
+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+------------------+
|      0|     1|        0|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      1|     0|       1|  0|      0|3.3336683417085426|
|      0|     0|        0|        0|       0|     0|    0|          0|    1|      1|        0|     0|      0|      0|      0|     0|       1|  0|      0|3.6714285714285713|
|      0|     1|        1|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0| 3.303370786516854|
|      0|     1|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     1|       0|  1|      0| 2.847926267281106|
|      0|     1|        0|        0|       0|     1|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|3.5324074074074074|
|      0|     0|        0|        0|       1|     0|    0|          0|    1|      1|        0|     0|      0|      0|      0|     1|       0|  0|      0|3.8333333333333335|
|      0|     1|        1|        0|       0|     0|    1|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0| 3.139817629179331|
|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      1|      0|      0|     0|       0|  0|      0| 3.110275689223058|
|      0|     0|        0|        0|       1|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|  3.34983498349835|
|      0|     1|        0|        0|       0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0| 4.149059334298118|
|      0|     0|        0|        0|       1|     1|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0| 3.902439024390244|
|      0|     1|        0|        0|       0|     1|    1|          0|    0|      0|        0|     1|      0|      0|      0|     0|       1|  0|      0| 3.119565217391304|
|      0|     0|        0|        0|       1|     0|    0|          0|    1|      1|        0|     0|      0|      0|      0|     0|       0|  0|      0|2.7884615384615383|
|      0|     1|        1|        0|       1|     0|    0|          0|    0|      1|        0|     0|      0|      0|      0|     0|       0|  0|      0|               3.0|
|      0|     0|        0|        1|       1|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|3.3613053613053614|
|      0|     1|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0| 4.156542056074766|
|      0|     0|        0|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      1|     0|       0|  1|      0| 3.488372093023256|
|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0| 4.018867924528302|
|      0|     1|        0|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      1|3.8613138686131387|
|      0|     1|        0|        1|       1|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     1|       1|  1|      0|           2.84375|
+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+------------------+
only showing top 20 rows